### ISSUE TITLE
[Bug]: The width is not correct for detected words

### ISSUE THREAD

**Issue by you-healthtap** [ocrmypdf/OCRmyPDF#1365]
### Describe the bug

Hi thanks for maintaining this lib, which is super useful for my image pdf use case. One thing I notice is:
The detected words width are alway one character shorter. Do you know the reason?
<img width="238" alt="Screenshot 2024-07-31 at 2 34 46 PM" src="https://github.com/user-attachments/assets/e9e14118-0b58-4869-a910-3d21ca523a86">

### Steps to reproduce

```plain text
Sorry that I can't attach the pdf since due to privacy reason. But below is the command I used

ocrmypdf --skip-text -l eng --rotate-pages --deskew --output-type pdfa  <pdf_path> <output_path>
```

### How did you download and install the software?

Linux package manager (apt, dnf, etc.)

### OCRmyPDF version

14.0.1+dfsg1-1

**Comment by jbarlow83** [comment]
That's a really old version - some of your issues are fixed in the latest.

**Comment by you-healthtap** [comment]
What is the right way to install latest?
The env is debian, and I tried to install ocrmypdf by pip. It needs some other requirements that are hard to meet. For example, Ghostscript only has 10.0.0 in  Debian12 (bookworm)

2024-08-02T02:14:06.291427535Z ocrmypdf.exceptions.MissingDependencyError: Ghostscript 10.0.0 through 10.02.0 (your version: 10.0.0) contain serious regressions that corrupt PDFs with existing text, such as those processed using --skip-text or --redo-ocr. Please upgrade to a newer version, or use --output-type pdf to avoid Ghostscript, or use --force-ocr to discard existing text.

**Comment by jbarlow83** [comment]
For Linux, I recommend Homebrew as the easiest way to get the latest versions of everything.

Homebrew is great for any point release Linux distribution where you need newer versions without disrupting your base system.

**Comment by you-healthtap** [comment]
@jbarlow83 I tried to add Homebrew into my dockerfile, but not easy to get things right. Anyway, I managered to install OCRmyPDF 16.4.2 with pip, and tesseract-ocr tesseract-ocr-eng ghostscript with apt.

However, even with the latest OCRmyPDF, I still see such isse. Below is the call I am using:
            ocrmypdf.ocr(pdf_path, output_path, force_ocr=True, output_type="pdf")
